import Foundation

/// Kurumsal (enterprise) seviye, API'siz Jira ticket üreticisi.
/// Yerel bug triyajını (LocalBugClassifier) kullanarak; yönetici özeti,
/// önceliklendirme, bug başına ayrı kırılım (kategori, güven, kök neden, kanıt,
/// repro adımları, kabul kriterleri), etki/sıklık ve ek listesi içeren
/// profesyonel bir hata bildirimi üretir.
enum JiraTicketBuilder {

    struct Artifacts {
        var screenshotPaths: [String] = []
        var videoPath: String?
        var tracePath: String?
        var htmlReportPath: String?
    }

    static func build(processName: String,
                      source: String,
                      logs: [LogEntry],
                      steps: [TestStep],
                      scenarioMarkdown: String?,
                      artifacts: Artifacts) -> String {
        let now = ISO8601DateFormatter().string(from: Date())
        let ticketID = "QA-" + String(Int(Date().timeIntervalSince1970) % 100000)

        // Yerel triyaj
        let verdicts = LocalBugClassifier.classify(logs)
        let bugs = logs.filter { verdicts[$0.id]?.isBug == true }
            .sorted { rank($0, verdicts) > rank($1, verdicts) }   // önem sırasına göre
        let noise = logs.filter { verdicts[$0.id]?.isBug != true }

        let priority = topPriority(bugs.compactMap { verdicts[$0.id]?.severity })
        let totalOccurrences = bugs.reduce(0) { $0 + $1.occurrenceCount }
        let components = Set(bugs.compactMap { verdicts[$0.id]?.component }.filter { !$0.isEmpty })
        let labels = Set(bugs.flatMap { verdicts[$0.id]?.labels ?? [] }).sorted()

        let summary = bugs.first.map { primaryBugSummary($0, verdicts) }
            ?? "Errors observed while testing \(processName) (no clear bug via local triage)"

        // ---- Belge ----
        var out = """
        # [\(ticketID)] \(summary)

        > _Auto-generated by QAioS (local, offline enterprise triage). No AI used._

        ## 1. Ticket Fields
        | Field | Value |
        |---|---|
        | **Issue Type** | Bug |
        | **Priority** | \(priority) |
        | **Severity** | \(bugs.first.flatMap { verdicts[$0.id]?.severity } ?? "—") |
        | **Component(s)** | \(components.isEmpty ? processName : components.sorted().joined(separator: ", ")) |
        | **Labels** | \(labels.isEmpty ? "qa, auto-detected" : labels.joined(separator: ", ")) |
        | **Environment** | \(source) · process `\(processName)` |
        | **Reporter** | QAioS (by SentinelAI) |
        | **Detected At** | \(now) |
        | **Frequency / Impact** | \(bugs.count) distinct bug(s), \(totalOccurrences) total occurrence(s) |

        ## 2. Executive Summary
        \(executiveSummary(bugs: bugs, noise: noise, verdicts: verdicts, process: processName))

        ## 3. Identified Bugs
        """

        if bugs.isEmpty {
            out += "\n_No application bugs were identified by local triage. All captured entries were classified as benign/noise (see Appendix A)._\n"
        } else {
            for (i, e) in bugs.enumerated() {
                out += "\n" + bugBlock(index: i + 1, entry: e, verdict: verdicts[e.id]!, steps: steps)
            }
        }

        // Repro adımları (genel)
        out += """

        ## 4. Steps to Reproduce (session)
        Auto-captured user actions, timestamped (aligns with the log records above):
        \(stepsDump(steps))
        \(scenarioMarkdown.map { "\n## 5. Scenario Verification\n\($0)\n" } ?? "")
        ## \(scenarioMarkdown == nil ? "5" : "6"). Attachments & Evidence
        \(attachmentsSection(artifacts))

        ## \(scenarioMarkdown == nil ? "6" : "7"). Acceptance Criteria
        \(acceptanceCriteria(bugs: bugs, verdicts: verdicts))

        ## Appendix A — Filtered-out (noise) entries
        _These were reviewed and classified as benign (framework/simulator/transient). Listed for completeness._
        \(noiseAppendix(noise: noise, verdicts: verdicts))

        ---
        _Priority/severity and categories derived by QAioS local rule engine. For AI-written root-cause narrative, use the “AI Ticket” action._
        """
        return out
    }

    // MARK: - Bug bloğu (her bug için ayrı, kurumsal kırılım)

    private static func bugBlock(index: Int, entry: LogEntry, verdict: BugVerdict, steps: [TestStep]) -> String {
        let occ = entry.occurrenceCount > 1 ? " · ×\(entry.occurrenceCount)" : ""
        var b = """
        ### 3.\(index) [\(verdict.severity)] \(verdict.category)\(occ)
        | | |
        |---|---|
        | **Message** | `\(entry.message.replacingOccurrences(of: "\n", with: " ").prefix(200))` |
        | **Category** | \(verdict.category) |
        | **Confidence** | \(verdict.confidence) |
        | **Component** | \(verdict.component.isEmpty ? "—" : verdict.component) |
        | **Signature** | `\(entry.signature)` |
        | **First seen** | \(entry.timestamp) |
        | **Occurrences** | \(entry.occurrenceCount) |

        **Why it's a bug:** \(verdict.reason)
        """
        if !verdict.rootCause.isEmpty {
            b += "\n**Heuristic root cause:** \(verdict.rootCause)"
        }
        if !entry.context.isEmpty {
            b += "\n\n<details><summary>Pre-error context</summary>\n\n```\n\(entry.context.joined(separator: "\n"))\n```\n</details>"
        }
        if let stack = entry.stackSample {
            b += "\n\n<details><summary>Call-stack sample (Instruments)</summary>\n\n```\n\(stack.prefix(1600))\n```\n</details>"
        }
        if let snap = entry.snapshot {
            b += "\n\n<details><summary>System snapshot at error time</summary>\n\n```\n\(snap.formatted)\n```\n</details>"
        }
        if let shot = entry.screenshotPath {
            b += "\n\n**Screenshot:** `\(shot)`"
        }
        // Bu bug'ın zamanına en yakın kullanıcı eylemi (repro ipucu)
        if let near = nearestStep(to: entry, steps: steps) {
            b += "\n\n**Likely trigger action:** \(near)"
        }
        b += "\n\n**Expected:** No \(verdict.category.lowercased()) occurs during this flow.\n**Actual:** \(verdict.severity == "Blocker" ? "The app terminates." : "The error is logged and the flow is affected.")\n"
        return b
    }

    // MARK: - Bölümler

    private static func executiveSummary(bugs: [LogEntry], noise: [LogEntry],
                                         verdicts: [UUID: BugVerdict], process: String) -> String {
        let cats = Dictionary(grouping: bugs, by: { verdicts[$0.id]?.category ?? "?" })
            .map { "\($0.value.count)× \($0.key)" }.sorted()
        let blockers = bugs.filter { verdicts[$0.id]?.severity == "Blocker" }.count
        var s = "During this test session on `\(process)`, QAioS captured \(bugs.count + noise.count) unique log entr\(bugs.count + noise.count == 1 ? "y" : "ies"); "
        s += "\(bugs.count) classified as application bug(s) and \(noise.count) as benign noise. "
        if blockers > 0 { s += "**\(blockers) blocker-level crash(es)** require immediate attention. " }
        if !cats.isEmpty { s += "Bug categories: \(cats.joined(separator: ", "))." }
        return s
    }

    private static func attachmentsSection(_ a: Artifacts) -> String {
        var lines: [String] = []
        if !a.screenshotPaths.isEmpty {
            lines.append("- Screenshots (\(a.screenshotPaths.count)):")
            lines += a.screenshotPaths.prefix(10).map { "    - `\($0)`" }
        }
        if let v = a.videoPath { lines.append("- Screen recording: `\(v)`") }
        if let t = a.tracePath { lines.append("- Instruments trace: `\(t)`") }
        if let h = a.htmlReportPath { lines.append("- HTML report: `\(h)`") }
        return lines.isEmpty ? "_No artifacts captured (enable capture in Settings)._" : lines.joined(separator: "\n")
    }

    private static func acceptanceCriteria(bugs: [LogEntry], verdicts: [UUID: BugVerdict]) -> String {
        guard !bugs.isEmpty else { return "- [ ] No application errors are logged during the tested flow." }
        return bugs.prefix(8).enumerated().map { i, e in
            let v = verdicts[e.id]!
            return "- [ ] (\(v.severity)) \(v.category) no longer occurs: `\(e.message.prefix(80))`"
        }.joined(separator: "\n")
    }

    private static func noiseAppendix(noise: [LogEntry], verdicts: [UUID: BugVerdict]) -> String {
        guard !noise.isEmpty else { return "_None._" }
        return noise.prefix(30).map { e in
            "- [\(e.severity.rawValue)] \(verdicts[e.id]?.category ?? "") — `\(e.message.prefix(90))`"
        }.joined(separator: "\n")
    }

    // MARK: - Yardımcılar

    private static func primaryBugSummary(_ e: LogEntry, _ v: [UUID: BugVerdict]) -> String {
        let cat = v[e.id]?.category ?? "Error"
        return "\(cat) in \(v[e.id]?.component ?? e.processName): \(e.message.prefix(80))"
    }

    private static func stepsDump(_ steps: [TestStep]) -> String {
        guard !steps.isEmpty else { return "_No user actions were captured._" }
        return steps.enumerated().map { i, s in
            "\(i + 1). [\(s.done ? "x" : " ")] \(TestStepStore.timeString(s.time)) — \(s.title)"
        }.joined(separator: "\n")
    }

    /// Bir hataya en yakın (aynı/önceki) kullanıcı eylemi metni.
    private static func nearestStep(to entry: LogEntry, steps: [TestStep]) -> String? {
        steps.last?.title    // basit: en son eylem (çoğu zaman tetikleyici odur)
    }

    private static let severityRank = ["Blocker": 4, "Critical": 3, "Major": 2, "Minor": 1, "None": 0]

    private static func rank(_ e: LogEntry, _ v: [UUID: BugVerdict]) -> Int {
        (severityRank[v[e.id]?.severity ?? "None"] ?? 0) * 1000 + e.occurrenceCount
    }

    private static func topPriority(_ severities: [String]) -> String {
        for level in ["Blocker", "Critical", "Major", "Minor"] where severities.contains(level) { return level }
        return severities.isEmpty ? "Minor" : "Major"
    }
}
